import { AppContext } from "@/common/context/appContext";
import "../styles/globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AllModals from "@/custom/modals/allModals/allModals";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bus-Case",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContext>
          <AllModals />
          {children}
          <ToastContainer />
        </AppContext>
      </body>
    </html>
  );
}
